### ISSUE TITLE
Install npm dependencies after running init

### ISSUE THREAD

**Issue by sendilkumarn** [sendilkumarn/webpack-addons-pwa#12]
Is there any way to install all the npm dependencies that we add via cli

ping @ev1stensberg

**Comment by ev1stensberg** [comment]
You mean through running the init command or all the ones in package.json?

**Comment by sendilkumarn** [comment]
through running the init command.

currently this generates `webpack.config.js` which will have few dependencies, but how to install them?

**Comment by ev1stensberg** [comment]
You can extend the generator, I think that should make it work

**Comment by Symphoria** [comment]
The default [Init Generator](https://github.com/webpack/webpack-cli/blob/master/lib/generators/init-generator.js) in webpack-cli uses an `installPlugins()` method that installs the dependencies through running the init command. Maybe we can take something from there? @sendilkumarn @ev1stensberg

**Comment by ev1stensberg** [comment]
yes

**Comment by Symphoria** [comment]
Can I take a crack at this?
@sendilkumarn @ev1stensberg Would ask if I get stuck anywhere

**Comment by ev1stensberg** [comment]
yes

**Comment by sendilkumarn** [comment]
ofcourse yeah 👍
