### ISSUE TITLE
Option to add the manifest file

### ISSUE THREAD

**Issue by sendilkumarn** [sendilkumarn/webpack-addons-pwa#2]
- [ ] To create a manifest file with minimal options like (color and name) if manifest is not available
- [ ] Option to link to existing manifest file
- [ ] Use `copywebpack` plugin to copy the manifest to build directory

**Comment by Symphoria** [comment]
@sendilkumarn Can we close this?

**Comment by sendilkumarn** [comment]
next time in PR add fixes this issue 👍 

closed by #4

**Comment by Symphoria** [comment]
Got it
